### ISSUE TITLE
[FEATURE REQUEST] Import through PDFs

### ISSUE THREAD

**Issue by vishalscodes** [Akylas/OSS-DocumentScanner#186] opened 2024-04-13 04:45 UTC
It would be nice if we could import PDFs into the app for photo additions and stuff. 

It helps to transition from my previous PDF scanning app to here.

The only other way to bring PDFs here is to convert it to images, which is tedious.

![Screenshot_20240413_101346_com indymobileapp document scanner~3](https://github.com/Akylas/OSS-DocumentScanner/assets/104351431/48383007-ecba-4401-846a-d53bbfc983c2)

**Comment by Tarek-Hasan** [comment] 2024-04-24 08:00
Duplicate of #138

**Closed** 2024-04-24 08:02 UTC
Labels: enhancement

**Comment by farfromrefug** [comment] 2024-04-27 19:43
@Tarek-Hasan @vishalscodes  it is now implemented in latest android version (ios to come later)
