### ISSUE TITLE
Pdf share

### ISSUE THREAD

**Issue by Jetrom17** [Akylas/OSS-DocumentScanner#129] opened 2024-02-13 20:06 UTC
### Version

version 1.4.4.45

### What platform are you using?

Android (Motorola)

### OS Version

Android 13

### What happened?

![Screenshot_20240213-165956](https://github.com/Akylas/OSS-DocumentScanner/assets/72875404/84709111-0fa0-4c85-a47e-7471a62d3e3f)

This happens when I click on the "pdf" icon to export accepting the name generated for the pdf. This displays the error making it impossible to share. I have this error since the previous version. That's why I'm reporting now.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by farfromrefug** [comment] 2024-02-14 10:27
@Jetrom17 thanks a lot for reporting this, and sorry for the trouble. Will fix it as soon as possible

**Comment by farfromrefug** [comment] 2024-02-14 16:25
@Jetrom17 a few questions?
* this happens when you do pdf button=>export=>enter name=>ok ?
* did you change the export folder or is it still set to `Downloads`?

**Comment by Jetrom17** [comment] 2024-02-14 17:46
> @Jetrom17 a few questions?
> * this happens when you do pdf button=>export=>enter name=>ok ?
> * did you change the export folder or is it still set to `Downloads`?

I didn't change anything. Either way this should handle any type of error. These are just and the only reports that I know how to tell you.

**Comment by farfromrefug** [comment] 2024-02-14 17:48
@Jetrom17 Dont worry i was not implying anything. I was just trying to understand where the error happens. 
I seems to be a permission issue that i cant reproduce . Will try more

**Comment by farfromrefug** [comment] 2024-02-15 20:54
@Jetrom17 i tried to get around this in 1.4.6. It might give you a new error now. If so please share the error

**Comment by Jetrom17** [comment] 2024-02-15 21:36
> @Jetrom17 i tried to get around this in 1.4.6. It might give you a new error now. If so please share the error

It's still the same error.

**Comment by farfromrefug** [comment] 2024-02-16 08:28
@Jetrom17 realy sorry to hear that. Could you to reproduce the issue with this build https://github.com/Akylas/OSS-DocumentScanner/releases/tag/test_android ? When the issue happen it should send be a bug report (please restart the app after the error to ensure the bug report is sent).
Thank you

**Comment by Jetrom17** [comment] 2024-02-18 00:22
> @Jetrom17 realy sorry to hear that. Could you to reproduce the issue with this build https://github.com/Akylas/OSS-DocumentScanner/releases/tag/test_android ? When the issue happen it should send be a bug report (please restart the app after the error to ensure the bug report is sent).
> Thank you

![Screenshot_20240217-212129.jpg](https://github.com/Akylas/OSS-DocumentScanner/assets/72875404/a2790822-42dc-4e67-9e95-8496f629f81e)

**Comment by farfromrefug** [comment] 2024-02-21 11:58
@Jetrom17 ok i see where the error happens. Now is the time to find why  :D
So it is a permission issue. It seems the app dont have the right to access that folder.
Did you create that folder from the app ?(clicking on the pdf button=>click on the export folder name at the top=> create the folder in the opening dialg=> give write permission)
if you create another folder, from the app, to export to, does it work?

**Comment by farfromrefug** [comment] 2024-02-21 13:04
@Jetrom17 why did you close the issue? I plan on fixing this. But some issues are not always easy to reproduce as there are so many "contexts" (different phones, os version, setup ...)

**Comment by farfromrefug** [comment] 2024-05-03 19:06
@Jetrom17 this should be fixed now

**Closed by farfromrefug** 2024-05-03 19:06 UTC
Labels: bug

**Comment by Jetrom17** [comment] 2024-05-03 21:27
> @Jetrom17 this should be fixed now

Thanks. I will be evaluating. Testing... Do you have personal contact via Telegram?

**Comment by farfromrefug** [comment] 2024-05-04 06:24
@Jetrom17 yes it is @farfromrefuge

**Comment by Jetrom17** [comment] 2024-05-04 11:40
> @Jetrom17 yes it is @farfromrefuge

`@YHVH7` - Is my.
